# Generated by Django 4.1 on 2022-09-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0002_actividades_provincias_usuarios_delete_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividades',
            old_name='provincia',
            new_name='codigo',
        ),
    ]
