# Generated by Django 4.1 on 2022-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0003_rename_provincia_actividades_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
