# Generated by Django 4.1 on 2022-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0004_alter_actividades_codigo_alter_provincias_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
