# Generated by Django 4.1 on 2022-09-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appblog', '0005_alter_actividades_codigo_alter_provincias_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.IntegerField()),
                ('codigo_provincia', models.IntegerField()),
                ('email_usuario', models.EmailField(max_length=254)),
                ('experiencia', models.TextField(max_length=140)),
                ('fecha_experiencia', models.DateField()),
            ],
        ),
    ]
